<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class farmasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["upaya_kesehatan" => "Farmasi", "kegiatan" => "Penyimpanan obat di ruang farmasi puskesmas", "satuan" => "checklist","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"penataan obat di ruang obat sudah sesai jenis sediaan dan menurut abjad" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Pelayanan Kefarmasian", "jenis_subindikator" => "Farmasi","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "Farmasi", "kegiatan" => "Penyimpanan obat di gudang farmasi puskesmas", "satuan" => "checklist","target_1" =>"5", "target_2" => "5",  "target_persen" => "100",  "target_des" =>"penataan obat di gudang obat sudah sesuai jenis sediaan dan menurut abjad, sistem FIFO dan FEFO, serta ada kartu stok yang terisi dengan benar" ,"pencapaian" =>"5","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Pelayanan Kefarmasian", "jenis_subindikator" => "Farmasi","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "Farmasi", "kegiatan" => "Meracik obat non racikan", "satuan" => "checklist","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"peracikan obat non racikan (tablet, kapsul, syrup) sesuai daftar tilik" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Pelayanan Kefarmasian", "jenis_subindikator" => "Farmasi","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "Farmasi", "kegiatan" => "Meracik obat racikan", "satuan" => "checklist","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"peracikan obat racikan (puyer) sesuai daftar tilik" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Pelayanan Kefarmasian", "jenis_subindikator" => "Farmasi","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "Farmasi", "kegiatan" => "Pengemasan dan pelabelan obat", "satuan" => "checklist","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Pelaksanaan pengemasan dan pelabelan obat sudah dilaksanakan denganbenar sesuai daftar tilik" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Pelayanan Kefarmasian", "jenis_subindikator" => "Farmasi","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "Farmasi", "kegiatan" => "Penyerahan obat", "satuan" => "checklist","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Pelaksanaan penyerahan obat yang sudah dilaksanakan sesuai dftar tilik" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Pelayanan Kefarmasian", "jenis_subindikator" => "Farmasi","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "Farmasi", "kegiatan" => "Penyimpanan/Penataan vaksin", "satuan" => "checklist","target_1" =>"6", "target_2" => "6",  "target_persen" => "100",  "target_des" =>"penataan dan penyimpanan vaksin sesuai standar" ,"pencapaian" =>"6","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Pelayanan Kefarmasian", "jenis_subindikator" => "Farmasi","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "Farmasi", "kegiatan" => "Penulisan resep yang rasional", "satuan" => "resep","target_1" =>"3", "target_2" => "3",  "target_persen" => "100",  "target_des" =>"penulisan resep sesuai dengan juknis Pemantauan Indikator Kinerja Kegiatan Penggunaan Obat Rasional Direktorat Pelayanan Kefarmasian Tahun 2017-2019" ,"pencapaian" =>"3","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Pelayanan Kefarmasian", "jenis_subindikator" => "Farmasi","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "Farmasi", "kegiatan" => "Pembinaan dan Pengawasan Apotek Jejaring Puskesmas yang menerapkan Pelayanan Farmasi Klinik", "satuan" => "checklist","target_1" =>"1", "target_2" => "1",  "target_persen" => "100",  "target_des" =>"Pembinaan dan Pengawasan Apotek Jejaring Puskesmas Yang menerapkan Pelayanan Farmasi Klinik meliputi : PIO, Konseling, MESO, Pencatatan Pengelolaan Pasien, Home Pharmacy Care" ,"pencapaian" =>"1","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Pelayanan Kefarmasian", "jenis_subindikator" => "Farmasi","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            
            
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Ketenagaan Laboratorium sesuai standar PMK Nomor 37 Th 2012 dan PMK No 43 Tahun 2019", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai Ketersedian ATLM yang kompeten sesuai standar PMK Nomor 37 Th 2012" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Tenaga","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Persyaratan minimal bangunan laboratorium puskesmas PMK 37 Tahun 2012 dan PMK 43 Th 2019", "satuan" => "nilai","target_1" =>"14", "target_2" => "14",  "target_persen" => "100",  "target_des" =>"Nilai observasi persyaratan bangunan Laboratorium sesuai standar" ,"pencapaian" =>"14","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Bangunan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Persyaratan minimal Prasarana laboratorium puskesmas sesuai standar PMK 37 Th 2012", "satuan" => "nilai","target_1" =>"8", "target_2" => "8",  "target_persen" => "100",  "target_des" =>"Nilai observasi persyaratan prasarana Laboratorium sesuai standar" ,"pencapaian" =>"8","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Prasarana","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Persyaratan minimal perlengkapan & peralatan laboratorium puskesmas sesuai PMK 37 Tahun 2012", "satuan" => "nilai","target_1" =>"50", "target_2" => "50",  "target_persen" => "100",  "target_des" =>"Nilai observasi perlengkapan dan peralatan Laboratorium sesuai standar" ,"pencapaian" =>"50","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Perlengkapan & Peralatan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Ketersediaan, kelengkapan dan ketertiban pengisian administrasi laboratorium ", "satuan" => "nilai","target_1" =>"9", "target_2" => "9",  "target_persen" => "100",  "target_des" =>"Nilai Ketersediaan, kelengkapan dan ketertiban administrasi Laboratorium" ,"pencapaian" =>"9","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Administrasi","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Pelaksanaan Kalibrasi", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai persyaratan alat laboratorium terkalibrasi " ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Pelaksanaan Pemantapan Mutu Eksternal ( PME)", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai Pelaksanaan Pemantapan Mutu Eksternal ( PME)" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Terdapat program pelatihan dan pendidikan berkelanjutan bagi setiap SDM laboratorium untuk meningkatkan ketrampilan, pengetahuan dan kompetensi.", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai kompetensi petugas laboratorium" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Pelaksanaan Simpus Laboratorium", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai Pelaksanaan Simpus Laboratorium" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Administrasi Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Tersedia & terisi stok reagen", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai ketersediaan dan kelengkapan isian stok reagen" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Administrasi Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Kepatuhan petugas analis terhadap SOP", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian Kepatuhan petugas analis terhadap SOP" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Kesiapan tenaga analis sesuai jam pelayanan puskesmas", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian Kesiapan tenaga analis sesuai jam pelayanan puskesmas" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Pelaksanaan Pemantapan Mutu Internal ( PMI )", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui Pelaksanaan Pemantapan Mutu Internal ( PMI )" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Kepatuhan Kebersihan Tangan", "satuan" => "nilai","target_1" =>"1", "target_2" => "1",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian Kepatuhan Kebersihan Tangan" ,"pencapaian" =>"1","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Kepatuhan Penggunaan Alat Pelindung Diri (APD)", "satuan" => "nilai","target_1" =>"1", "target_2" => "1",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian Kepatuhan Penggunaan Alat Pelindung Diri (APD)" ,"pencapaian" =>"1","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Kepatuhan Identifikasi Pasien", "satuan" => "nilai","target_1" =>"1", "target_2" => "1",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian Kepatuhan Identifikasi Pasien" ,"pencapaian" =>"1","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Kepatuhan Pelaporan Hasil Kritis", "satuan" => "nilai","target_1" =>"1", "target_2" => "1",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian Kepatuhan Pelaporan Hasil Kritis" ,"pencapaian" =>"1","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Kejadian Sampel/Spesimen Hilang", "satuan" => "nilai","target_1" =>"1", "target_2" => "1",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian Kejadian Sampel/Spesimen Hilang" ,"pencapaian" =>"1","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Pengulangan Hasil Pemeriksaan", "satuan" => "nilai","target_1" =>"1", "target_2" => "1",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian Pengulangan Hasil Pemeriksaan" ,"pencapaian" =>"1","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Laboratorium menetapkan waktu tunggu pemeriksaan laboratorium", "satuan" => "nilai","target_1" =>"1", "target_2" => "1",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian waktu tunggu pemeriksaan laboratorium" ,"pencapaian" =>"1","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Pemantauan suhu harian kulkas reagen dan ruangan;", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian Pemantauan suhu harian kulkas reagen dan ruangan" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Pemeliharaan alat", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian Pemeliharaan alat" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Setiap reagen diberi label yang berisi informasi lengkap dan akurat.", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian kelengkapan dan keakuratan informasi labelling reagen" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Angka kejadian kecelakaan kerja pada petugas di laboratorium", "satuan" => "nilai","target_1" =>"1", "target_2" => "1",  "target_persen" => "100",  "target_des" =>"Nilai Mutu pelayanan laboratorium melalui penilaian Angka kejadian kecelakaan kerja pada petugas di laboratorium" ,"pencapaian" =>"1","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Peningkatan Mutu Pelayanan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Kegiatan Laboratorium di Luar Gedung", "satuan" => "nilai","target_1" =>"2", "target_2" => "2",  "target_persen" => "100",  "target_des" =>"Nilai pelaksanaan Kegiatan Laboratorium di Luar Gedung" ,"pencapaian" =>"2","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Kegiatan di luar gedung","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            
            ["upaya_kesehatan" => "LAB", "kegiatan" => "Pendapatan Laboratorium bulanan", "satuan" => "nilai","target_1" =>"1", "target_2" => "1",  "target_persen" => "100",  "target_des" =>"Nilai kedisiplinan pelaporan pendapatan laboratorium " ,"pencapaian" =>"1","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "Laboratorium", "jenis_subindikator" => "Pendapatan","cakupan" => "a","sub_variabel" => "100","nilai" => "100","tahun" =>"2024","bulan"=>"6"],
            
            
            
            // ["upaya_kesehatan" => "", "kegiatan" => "", "satuan" => "","target_1" =>"", "target_2" => "",  "target_persen" => "",  "target_des" =>"" ,"pencapaian" =>"","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "", "jenis_subindikator" => "","cakupan" => "","sub_variabel" => "","nilai" => "","tahun" =>"2024","bulan"=>"6"],
            
            
            // ["upaya_kesehatan" => "", "kegiatan" => "", "satuan" => "","target_1" =>"", "target_2" => "",  "target_persen" => "",  "target_des" =>"" ,"pencapaian" =>"","jenis_cakupan" => "Farmasi & Lab", "jenis_indikator" => "", "jenis_subindikator" => "","cakupan" => "","sub_variabel" => "","nilai" => "","tahun" =>"","bulan"=>"","akun_puskesmas" => ""],
          
        ];
        
        
        
        DB::table('tbl_sinikimas_pkp')->insert($data);
        
    }
}
