<?php

namespace Database\Seeders\tblManajemen;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class srondolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = [
            
            ["indikator" => "Manajemen Umum Perpustakaan", "sub_indikator" => "Manajemen Umum Perpustakaan", "jenis_variabel" => "Mempunyai Rencana Lima Tahunan (RSB)", "nilai_0" => "tidak punya", "nilai_4" => "-", "nilai_7" => "-", "nilai_10" => "punya", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Umum Perpustakaan", "sub_indikator" => "Manajemen Umum Perpustakaan", "jenis_variabel" => "Ada RUK, disusun berdasarkan Rencana Lima Tahunan dan melalui analisis situasi dan perumusan masalah", "nilai_0" => "tidak menyusun", "nilai_4" => "ya , beberapa ada analisa dan perumusan", "nilai_7" => "ya, sebagian ada analisa dan perumusan", "nilai_10" => "ya, seluruhnya ada analisa dan perumusan", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Umum Perpustakaan", "sub_indikator" => "Manajemen Umum Perpustakaan", "jenis_variabel" => "menyusun RPK secara terinci dan lengkap", "nilai_0" => "tidak menyusun", "nilai_4" => "ya terinci sebagian kecil", "nilai_7" => "ya, terinci sebagian besar", "nilai_10" => "ya, terinci semuanya", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Umum Perpustakaan", "sub_indikator" => "Manajemen Umum Perpustakaan", "jenis_variabel" => "melaksanakan mini lokakarya bulanan", "nilai_0" => "tidak melaksanakan", "nilai_4" => "< 5 kali/ tahun", "nilai_7" => "5-8 kali/tahun", "nilai_10" => "9-12 kali/tahun", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Umum Perpustakaan", "sub_indikator" => "Manajemen Umum Perpustakaan", "jenis_variabel" => "melaksanakan mini lokakarya tribulanan", "nilai_0" => "tidak melaksanakan", "nilai_4" => "< 2 kali/tahun", "nilai_7" => "2-3 kali/tahun", "nilai_10" => "4 kali/ tahun", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Umum Perpustakaan", "sub_indikator" => "Manajemen Umum Perpustakaan", "jenis_variabel" => "membuat Penilaian Kinerja di tahun sebelumnya, mengirimkan ke dinas kesehatan kota dan mendapat feedback dari dinas kesehatan kota", "nilai_0" => "tidak membuat", "nilai_4" => "membuat tetapi tidak mengirimkan", "nilai_7" => "membuat dan mengirimkan tetapi tidak mendapatkan feedback", "nilai_10" => "membuat, mengirimkan dan mendapat feedback dari dinas kesehatan kota", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            
            
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Peralatan (medik/ non medik)", "jenis_variabel" => "Kartu inventaris peralatan di semua ruangan", "nilai_0" => "Tidak punya dokumen", "nilai_4" => "ya,membuat namun belum semua ruangan", "nilai_7" => "ya,membuat namun belum terdokumentasikan", "nilai_10" => "Membuat kartu inventaris & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Peralatan (medik/ non medik)", "jenis_variabel" => "Mengupdate daftar inventaris alat", "nilai_0" => "Tidak punya dokumen", "nilai_4" => "ya,melaksanakan updateting barang namun belum semuanya", "nilai_7" => "ya,melaksanakan update daftar inventaris namun belum terdokumentasikan", "nilai_10" => "Meng update inventaris barang  & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Peralatan (medik/ non medik)", "jenis_variabel" => "Membuat laporan inventaris alat", "nilai_0" => "Tidak punya dokumen", "nilai_4" => "ya,membuat laporan inentaris namun belum semua alat", "nilai_7" => "ya,sudah membuat laporan,namun belum terdokumentasikan", "nilai_10" => "Membuat laporan Inventaris & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Peralatan (medik/ non medik)", "jenis_variabel" => "Menyusun rencana & mengajukan kebutuhan alat", "nilai_0" => "Tidak punya dokumen", "nilai_4" => "ya,membuat rencana usulan kebutuhan alat", "nilai_7" => "ya,membuat usulan kebutuhan alat namun belum terealisasi sesuai permintaan", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Peralatan (medik/ non medik)", "jenis_variabel" => "Pengamanan aset", "nilai_0" => "Tidak punya dokumen", "nilai_4" => "-", "nilai_7" => "-", "nilai_10" => "Dilakukan pengamanan aset & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Peralatan (medik/ non medik)", "jenis_variabel" => "Pemeliharaan peralatan", "nilai_0" => "Tidak punya dokumen", "nilai_4" => "ya,melaksanakan pemeliharaan alat,namun belum semuanya", "nilai_7" => "ya,melaksanakan pemeliharaan,namun belum ada dokumennya", "nilai_10" => "Dilakukan Pemeliharaan dan ada Dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Peralatan (medik/ non medik)", "jenis_variabel" => "Mendistribusikan/mencatat aset pada Masing-masing KIB (kartu Inventaris Barang) Mulai Dari KIB A s/d KIB F", "nilai_0" => "Tidak punya dokumen", "nilai_4" => "ya, sudah mencatat, namun belum sesuai", "nilai_7" => "ya, mendistribusikan/menatat aset, Nmun belum terdokumentasikan", "nilai_10" => "Melakukan pencatatan/ pendistribusian sesuai dengan KIB, dan ada dokumentasi", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Peralatan (medik/ non medik)", "jenis_variabel" => "Update aspak", "nilai_0" => "Tidak dilaksanakan", "nilai_4" => "dilaksanakan 1 tahun 1 kali", "nilai_7" => "-", "nilai_10" => "dilaksanakan 1 tahun 2 kali", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen obat/bahan", "jenis_variabel" => "Daftar inventaris obat", "nilai_0" => "Tidak melaksanakan", "nilai_4" => "dilakukan oleh pengelola obat", "nilai_7" => "dilakukan oleh pengelola obat dan dilakukan setiap bulan sekali", "nilai_10" => "dilakukan oleh pengelola obat dan dilakukan setiap bulan sekali daftar sesuai dan diisi dengan benar", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen obat/bahan", "jenis_variabel" => "Pengajuan kebutuhan obat/bahan", "nilai_0" => "Tidak melaksanakan", "nilai_4" => "dilakukan oleh kepala puskesmas dilakukan oleh APJ (Apoteker Penanggung Jawab)", "nilai_7" => "dilakukan oleh APJ (Apoteker Penanggung Jawab) di setujui oleh kepala puskesmas", "nilai_10" => "dilakukan oleh APJ (Apoteker Penanggung Jawab) di setujui oleh kepala puskesmas dan format sesuai serta diisi dengan betul", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen obat/bahan", "jenis_variabel" => "Pemeriksaan kartu stok obat", "nilai_0" => "Tidak melaksanakan", "nilai_4" => "Dilakukan oleh kepala puskesmas atau pegawai yang diberi tugas dan di lakukan 1 bulan sekali secara sampling serta diberi paraf", "nilai_7" => "Dilakukan oleh kepala puskesmas atau pegawai yang diberi tugas dan di lakukan 1 bulan sekali secara sampling serta diberi paraf, sesuai antara kartu stok dan fisik", "nilai_10" => "Dilakukan oleh kepala puskesmas atau pegawai yang diberi tugas dan di lakukan 1 bulan sekali secara sampling serta diberi paraf, sesuai antara kartu stok dan fisik, format dan cara pengisian betul", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen obat/bahan", "jenis_variabel" => "Pencatatan kartu suhu", "nilai_0" => "Tidak melaksanakan", "nilai_4" => "diperiksa oleh pengelola obat dan dilakukan setiap hari", "nilai_7" => "diperiksa oleh pengelola obat dan dilakukan setiap hari, suhu cold chain 2-8 ◦C", "nilai_10" => "diperiksa oleh pengelola obat dan dilakukan 3 kali setiap hari, suhu cold chain 2-8 ◦C bila format dan pengisian betul", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen obat/bahan", "jenis_variabel" => "pencatatan penggunaan obat", "nilai_0" => "Tidak melaksanakan", "nilai_4" => "dilakukan oleh pengelola obat dan dilakukan setiap hari", "nilai_7" => "dilakukan oleh pengelola obat dan dilakukan setiap hari, pencatatan dibuat perlembar resep", "nilai_10" => "dilakukan oleh pengelola obat dan dilakukan setiap hari, pencatatan dibuat perlembar resep, format dan pengisian betul", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen obat/bahan", "jenis_variabel" => "Pembuatan LPLPO", "nilai_0" => "Tidak melaksanakan", "nilai_4" => "dilakukan oleh pengelola obat", "nilai_7" => "dilakukan oleh pengelola obat, pelaporan ke DKK sebelum tanggal 10", "nilai_10" => "dilakukan oleh pengelola obat, pelaporan ke DKK sebelum tanggal 10, format dan pengisian betul", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen obat/bahan", "jenis_variabel" => "Pemusnahan obat/ bahan kadaluwarsa", "nilai_0" => "Tidak melaksanakan", "nilai_4" => "dilakukan pemisahan obat atau bahan-bahan kadaluarsa dan/atau rusak 1 bulan sekali (apabila ditemukan)", "nilai_7" => "dilakukan pemisahan dan pencatatan obat atau bahan-bahan kadaluarsa dan/atau rusak 1 bulan sekali (apabila ditemukan) ", "nilai_10" => "dilakukan pemisahan dan pencatatan obat atau bahan-bahan kadaluarsa dan/atau rusak 1 bulan sekali (apabila ditemukan) diserahkan ke instalasi farmasi sesuai jadwal yang di tentukan", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen obat/bahan", "jenis_variabel" => "Kegiatan stock opname", "nilai_0" => "Tidak melaksanakan", "nilai_4" => "dilakukan oleh pengelola obat dan dilakukan minimal satu tahun sekali", "nilai_7" => "dilakukan oleh pengelola obat dan dilakukan minimal satu tahun sekali, sesuai antara fisik dan kartu stok", "nilai_10" => "dilakukan oleh pengelola obat dan dilakukan minimal satu tahun sekali, sesuai antara fisik dan kartu stok serta format dan pengisian betul", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen obat/bahan", "jenis_variabel" => "Pengadaan Obat dan BMHP (Bahan Medis Habis Pakai) termasuk bahan gigi dan reagen", "nilai_0" => "Tidak menggunakan Surat Pesanan", "nilai_4" => "Pengadaan Obat dan BMHP menggunakan SP (Surat Pesanan) yang di tanda tanggani oleh APJ yang SIPAnya tidak aktif", "nilai_7" => "Pengadaan Obat dan BMHP menggunakan SP (Surat Pesanan) yang di tanda tanggani oleh APJ ber SIPA aktif", "nilai_10" => "Pengadaan Obat dan BMHP menggunakan SP (Surat Pesanan) yang di tanda tanggani oleh APJ ber SIPA aktif dan di ketahui oleh kepala puskesmas", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Tenaga", "jenis_variabel" => "Daftar urut kepangkatan pegawai", "nilai_0" => "Tidak ada", "nilai_4" => "Ada belum diubah tidak terpasang", "nilai_7" => "Ada belum diubah, terpasang", "nilai_10" => "Ada, telah diubah dan terpasang", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Tenaga", "jenis_variabel" => "Buku penjagaan  KGB", "nilai_0" => "Tidak ada", "nilai_4" => "% penjagaan KGB di Tindak lanjuti <75 %", "nilai_7" => "% penjagaan KGB di Tindak lanjuti <100 %", "nilai_10" => "100% penjagaan KGB di Tindak lanjuti", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Tenaga", "jenis_variabel" => "Buku penjagaan kenaikan pangkat", "nilai_0" => "Tidak ada", "nilai_4" => "% penjagaan KP  MS yang diusulkan <75 %", "nilai_7" => "% penjagaan KP  MS yang  diusulkan <75%", "nilai_10" => "100% penjagaan KP  MS yang diusulkan", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Tenaga", "jenis_variabel" => "Buku Penjagaan pesiun", "nilai_0" => "Tidak ada", "nilai_4" => "% penjagaan Pensiun yang diusulkan  min 6 bln sebelum BUP <75 %", "nilai_7" => "% penjagaan Pensiun yang diusulkan  min 6 bln sebelum BUP < 100 %", "nilai_10" => "100% penjagaan Pensiun yang diusulkan  min 6 bln sebelum BUP", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Tenaga", "jenis_variabel" => "Buku Penjagaan Cuti", "nilai_0" => "Tidak terupdate", "nilai_4" => "0", "nilai_7" => "0", "nilai_10" => "Penjagaan cuti terupdate", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Tenaga", "jenis_variabel" => "Absensi kehadiran ASN", "nilai_0" => "-", "nilai_4" => "% ketepatan waktu < 75 %", "nilai_7" => "% ketepatan waktu < 100 %", "nilai_10" => "% ketepatan waktu 100 %", "nilai_hasil" => "7", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Tenaga", "jenis_variabel" => "Absensi kehadiran Non ASN", "nilai_0" => "-", "nilai_4" => "% ketepatan waktu < 75 %", "nilai_7" => "% ketepatan waktu < 100 %", "nilai_10" => "% ketepatan waktu 100 %", "nilai_hasil" => "7", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Tenaga", "jenis_variabel" => "Buku Catatan Kenaikan Jabatan/Alih Kategori", "nilai_0" => "Tidak ada", "nilai_4" => "-", "nilai_7" => "-", "nilai_10" => "ada", "nilai_hasil" => "7", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Tenaga", "jenis_variabel" => "Buku catatan mutasi", "nilai_0" => "Tidak ada", "nilai_4" => "-", "nilai_7" => "-", "nilai_10" => "ada", "nilai_hasil" => "7", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Tenaga", "jenis_variabel" => "Buku catatan disiplin pegawai", "nilai_0" => "Tidak ada", "nilai_4" => "-", "nilai_7" => "-", "nilai_10" => "ada", "nilai_hasil" => "7", "akun_puskesmas" => "Srondol"],
            
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Sumber Daya Manusia Kesehatan", "jenis_variabel" => "Kepemilikan Surat Ijin Praktek Tenaga Kesehatan", "nilai_0" => "tidak memiliki SIP", "nilai_4" => "memiliki SIP tapi telah habis masa berlaku (kadaluarsa)", "nilai_7" => "saat ini dalam proses pengajuan SIP", "nilai_10" => "memiliki SIP yang masih berlaku", "nilai_hasil" => "7", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Sumber Daya Manusia Kesehatan", "jenis_variabel" => "Pembuatan ABK Kesehatan", "nilai_0" => "tidak membuat ABK", "nilai_4" => "membuat ABK tapi tidak sesuai aplikasi", "nilai_7" => "ABK Kesehatan dalam proses", "nilai_10" => "membuat ABK Kesehatan sesuai aplikasi sampai selesai", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Sumber Daya Manusia Kesehatan", "jenis_variabel" => "Updating data di aplikasi SISDMK Kementrian Kesehatan", "nilai_0" => "tidak mengupdate data SDMK sama sekali", "nilai_4" => "update data SDMK belum selesai", "nilai_7" => "update data SDMK secara keseluruhan tidak sesuai aplikasi web", "nilai_10" => "update data SDMK secara keseluruhan  sesuai aplikasi web", "nilai_hasil" => "7", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Sumber Daya", "sub_indikator" => "Manajemen Sumber Daya Manusia Kesehatan", "jenis_variabel" => "Monitoring SIP/STR Tenaga Kesehatan Jejaring", "nilai_0" => "Tidak melaksanakan", "nilai_4" => "-", "nilai_7" => "Melaksanakan 1 kali tiap tahun", "nilai_10" => "Melaksanakan 2 kali tiap tahun", "nilai_hasil" => "7", "akun_puskesmas" => "Srondol"],
            
            
            
            
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara Penerimaan Pembantu", "jenis_variabel" => "Membuat Buku Kas Umum (BKU) penerima yg ditanda tangani kepala puskesmas tiap bulan", "nilai_0" => "Tidak punya dokumen", "nilai_4" => "ya,sudah dibuat tp belum rutin setiap bulan", "nilai_7" => "Ya,sd dibuat Stp blm ditanda tangan pimpinan", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara Penerimaan Pembantu", "jenis_variabel" => "Membuat Buku Bantu Rincian Obyek penerimaan (umum,tindakan,laborat,RI/RB)", "nilai_0" => "Tidak punya dokumen", "nilai_4" => "ya,sudah dibuat tp belum rutin setiap bulan", "nilai_7" => "Ya,sd dibuat tp blm semua rincian objek", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara Penerimaan Pembantu", "jenis_variabel" => "Membuat Buku Rekapitulasi Penerimaan", "nilai_0" => "Tidak punya dokumen", "nilai_4" => "ya,sudah dibuat tp belum rutin setiap bulan", "nilai_7" => "ya,sudah membuat tetapi belum terdokumenkan", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara Penerimaan Pembantu", "jenis_variabel" => "Membuat laporan penerimaan (spj fungsional)", "nilai_0" => "Tidak punya dokumen", "nilai_4" => "ya,sudah dibuat tp belum rutin setiap bulan", "nilai_7" => "ya,sudah membuat tetapi belum terdokumenkan", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara Penerimaan Pembantu", "jenis_variabel" => "Pemeriksaan Kas tiap 3 (tiga)bulan sekali dengan berita acara pemeriksaan Kas", "nilai_0" => "Tidak punya dokumen", "nilai_4" => "ya,sudah dibuat tp belum rutin setiap 3 bulan", "nilai_7" => "ya,sudah membuat tetapi belum terdokumenkan", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara Pengeluaran Pembantu", "jenis_variabel" => "Membuat rencana kegiatan anggaran ( RKA)", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,sudah dibuat tp belum terdokumen", "nilai_7" => "ya,sd membuat tetapi masih belum lengkap", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara Pengeluaran Pembantu", "jenis_variabel" => "Membuat Buku Kas Umum (BKU) penerima yg ditanda tangani kepala puskesmas tiap bulan", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,sudah dibuat tp belum rutin setiap bulan", "nilai_7" => "Ya,sd dibuat tp blm ditanda tangan pimpinan", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara Pengeluaran Pembantu", "jenis_variabel" => "Membuat buku pembantu (simpanan Bank,Kas Tunai,Pajak dan buku rekapitulasi pengeluaran", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,sudah membuat buku bantu,namun belum lengkap", "nilai_7" => "ya, sudah membuat namun belum terdokumen", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara Pengeluaran Pembantu", "jenis_variabel" => "Membuat laporan keuangan (SP2D,SPJ)", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,sudah membuat laporan keuangan,namun belum lengkap", "nilai_7" => "ya, sudah membuat namun belum terdokumen", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara Pengeluaran Pembantu", "jenis_variabel" => "Membuat laporan pajak ( kekantor pajak)", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,sudah membuat laporan pajak,namun belum lengkap", "nilai_7" => "ya, sudah membuat namun belum terdokumen", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara Pengeluaran Pembantu", "jenis_variabel" => "Pemeriksaan Kas tiap 3 (tiga)bulan sekali dengan berita acara pemeriksaan Kas", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,melaksanakan pemeriksaan kas,namun belum secara rutin setiap 3 bulan", "nilai_7" => "ya,sudah melaksanakan pemeriksaan kas namun belum ada berita acara hasil pemeriksaan kas", "nilai_10" => "Melaksanakan pemeriksaan kas setiap 3 bulan sekali & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara BLUD", "jenis_variabel" => "RSB", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,membuat namun belum sempurna", "nilai_7" => "ya, membuat namun belum terdokumentasikan", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara BLUD", "jenis_variabel" => "RBA", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,membuat namun belum sempurna", "nilai_7" => "ya, membuat namun belum terdokumentasikan", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara BLUD", "jenis_variabel" => "SPP/SPM/SP2D/ BLUD", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,membuat namun belum sempurna", "nilai_7" => "ya,membuat namun belum sempurna", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara BLUD", "jenis_variabel" => "Surat Pernyataan tanggung jawab mutlak", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,membuat surat pernyataan tanggung jawab namun belum ditanda tangan", "nilai_7" => "ya,membuat surat pernyataan tanggung jawab namun masi ada revisi", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara BLUD", "jenis_variabel" => "Laporan belanja BLUD bulanan", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,membuat namun belum sempurna", "nilai_7" => "ya,membuat namun belum sempurna", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara BLUD", "jenis_variabel" => "Laporan realisasi anggaran (LRA) BLUD", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,membuat namun belum sempurna", "nilai_7" => "ya,membuat namun belum sempurna", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara BLUD", "jenis_variabel" => "Laporan perubahan SAL", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,membuat namun belum sempurna", "nilai_7" => "ya,membuat namun belum sempurna", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara BLUD", "jenis_variabel" => "Neraca", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,membuat namun belum sempurna", "nilai_7" => "ya,membuat namun belum sempurna", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara BLUD", "jenis_variabel" => "Laporan Operasional BLUD ( LO)", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,membuat namun belum sempurna", "nilai_7" => "ya,membuat namun belum sempurna", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara BLUD", "jenis_variabel" => "Laporan Arus Kas (LAK)", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,membuat namun belum sempurna", "nilai_7" => "ya,membuat namun belum sempurna", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara BLUD", "jenis_variabel" => "Laporan perubahan Ekuitas ( LPE)", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,membuat namun belum sempurna", "nilai_7" => "ya,membuat namun belum sempurna", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Bendahara BLUD", "jenis_variabel" => "CaLK", "nilai_0" => "Tdk punya dokumen", "nilai_4" => "ya,membuat namun belum sempurna", "nilai_7" => "ya,membuat namun belum sempurna", "nilai_10" => "Membuat & Tersedia dokumen", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Kepatuhan Pengelolaan Keuangan", "jenis_variabel" => "Rasio Pencapaian Target Pendapatan", "nilai_0" => "Belum mencapai Target masih dibawah 70%", "nilai_4" => "Ada dokumen, namun baru mencapai target 71-80%", "nilai_7" => "Ada dokumen, namun baru mencapai target 81-99%", "nilai_10" => "Ada dokumen dan Telah mencapai Target 100%", "nilai_hasil" => "7", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Kepatuhan Pengelolaan Keuangan", "jenis_variabel" => "Rasio Serapan Belanja", "nilai_0" => "Belum mencapai Target masih dibawah 70%", "nilai_4" => "Ada dokumen, namun baru mencapai target 71-80%", "nilai_7" => "Ada dokumen, namun baru mencapai target 81-99%", "nilai_10" => "Ada dokumen dan Telah mencapai Target 100%", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Kepatuhan Pengelolaan Keuangan", "jenis_variabel" => "ketepatan upload TBP", "nilai_0" => "lebih dari tanggal 5", "nilai_4" => "-", "nilai_7" => "kurang dari tanggal 5", "nilai_10" => "kurang dari tanggal 4", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Keuangan dan BMN/BMD", "sub_indikator" => "Kepatuhan Pengelolaan Keuangan", "jenis_variabel" => "ketepatan pengumpulan SPJ Fungsional", "nilai_0" => "lebih dari tanggal 10", "nilai_4" => "-", "nilai_7" => "tanggal 6-10", "nilai_10" => "kurang dari tanggal 5", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            
            
            
            ["indikator" => "Manajemen Data dan Informasi", "sub_indikator" => "Manajemen Data dan Informasi", "jenis_variabel" => "Ditetapkan Tim Sistem Informasi Puskesmas", "nilai_0" => "tidak ditetapkan", "nilai_4" => "-", "nilai_7" => "-", "nilai_10" => "ditetapkan", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Data dan Informasi", "sub_indikator" => "Manajemen Data dan Informasi", "jenis_variabel" => "Pengisian laporan Sistem Informasi Puskesmas Tepat Waktu", "nilai_0" => "tidak melaporkan", "nilai_4" => "persentase < 60 %", "nilai_7" => "persentase 61-79 %", "nilai_10" => "persentase 80-100 %", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Data dan Informasi", "sub_indikator" => "Manajemen Data dan Informasi", "jenis_variabel" => "Pengisian laporan Sistem Informasi Puskesmas lengkap", "nilai_0" => "tidak melaporkan", "nilai_4" => "persentase < 60 %", "nilai_7" => "persentase 61-79 %", "nilai_10" => "persentase 80-100 %", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Data dan Informasi", "sub_indikator" => "Manajemen Data dan Informasi", "jenis_variabel" => "Membuat profil Puskesmas", "nilai_0" => "tidak membuat", "nilai_4" => "membuat versi file", "nilai_7" => "membuat versi file dan cetak", "nilai_10" => "membuat versi file, cetak dan dipublikasikan", "nilai_hasil" => "4", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Data dan Informasi", "sub_indikator" => "Manajemen Data dan Informasi", "jenis_variabel" => "Pelaksanaan SIMPUS", "nilai_0" => "Tidak dilaksanakan", "nilai_4" => "Dilaksanakan di Loket pendaftaran", "nilai_7" => "Dilaksanakan di Loket pendaftaran, BP umum, BP Gigi", "nilai_10" => "Dilaksanakan di Loket pendaftaran, BP umum, BP Gigi, poli KIA, poli MTBS, poli lansia dan farmasi", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Data dan Informasi", "sub_indikator" => "Manajemen Data dan Informasi", "jenis_variabel" => "Melakukan pencadangan data (back up) data SIMPUS", "nilai_0" => "Tidak dilaksanakan", "nilai_4" => "dilaksanakan < 5 kali", "nilai_7" => "diilaksanakan 6-8 kali", "nilai_10" => "dilaksanakan >8 kali", "nilai_hasil" => "4", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Data dan Informasi", "sub_indikator" => "Manajemen Data dan Informasi", "jenis_variabel" => "Jangkauan akun instagram puskesmas", "nilai_0" => "menghasilkan nilai '-' pada engagement", "nilai_4" => "Menghasilkan nilai '+0,01 s/d +0.05' pada engagement", "nilai_7" => "Menghasilkan nilai '+0.06 s/d +0.1' pada engagement", "nilai_10" => "Menghasilkan nilai '+0.1 keatas' pada engagement", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Data dan Informasi", "sub_indikator" => "Manajemen Data dan Informasi", "jenis_variabel" => "Interaksi akun instagram Puskesmas", "nilai_0" => "menghasilkan nilai '-' pada engagement", "nilai_4" => "Menghasilkan nilai '+0,01 s/d +0.05' pada engagement", "nilai_7" => "Menghasilkan nilai '+0.06 s/d +0.1' pada engagement", "nilai_10" => "Menghasilkan nilai '+0.1 keatas' pada engagement", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Data dan Informasi", "sub_indikator" => "Manajemen Data dan Informasi", "jenis_variabel" => "Pengikut akun instagram Puskesmas", "nilai_0" => "menghasilkan nilai '-' pada engagement", "nilai_4" => "Menghasilkan nilai '+0,01 s/d +0.05' pada engagement", "nilai_7" => "Menghasilkan nilai '+0.06 s/d +0.1' pada engagement", "nilai_10" => "Menghasilkan nilai '+0.1 keatas' pada engagement", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Data dan Informasi", "sub_indikator" => "Manajemen Data dan Informasi", "jenis_variabel" => "Pengiriman laporan pelayanan dan kunjungan sarana kesehatan klinik ke Puskesmas", "nilai_0" => "tidak melaporkan", "nilai_4" => "persentase < 60 %", "nilai_7" => "persentase 61-79 %", "nilai_10" => "persentase 80-100 %", "nilai_hasil" => "0", "akun_puskesmas" => "Srondol"],
            
            
            
            ["indikator" => "Manajemen Program", "sub_indikator" => "Pendekatan Keluarga Sehat", "jenis_variabel" => "Pendataan PIS-PK", "nilai_0" => "Melakukan pendataan PIS-PK < 168 kk", "nilai_4" => "Melakukan pendataan PIS-PK  252 KK", "nilai_7" => "Melakukan pendataan 336 KK", "nilai_10" => "Melakukan Pendataan >/=420 KK", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Program", "sub_indikator" => "Pendekatan Keluarga Sehat", "jenis_variabel" => "Intervensi awal", "nilai_0" => "Melakukan Intervensi < 168", "nilai_4" => "Melakukan Intervensi awal 252 KK", "nilai_7" => "Melakukan Intervensi awal 336 KK", "nilai_10" => "Melakukan Intervensi awal >/=420 KK", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Program", "sub_indikator" => "Pendekatan Keluarga Sehat", "jenis_variabel" => "Intervensi lanjut", "nilai_0" => "Melakukan Intervensi lanjut, IKS<0,5", "nilai_4" => "MelakukanIntervensi Lanjut IKS 0,5--0,7", "nilai_7" => "Melakukan Intervensi Lanjut , IKS 0,7-0,80", "nilai_10" => "Melakukan Intervensi Lanjut , IKS >0,81", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Program", "sub_indikator" => "Pendekatan Keluarga Sehat", "jenis_variabel" => "Monitoring Evaluasi", "nilai_0" => "Tidak Melakukan Monev PIS_PK Tidak mempunyai SK PIS-PK", "nilai_4" => "Melakukan monev PIS_PK min setahun sekali, punya SK PIS-PK dan Analisis Data", "nilai_7" => "Melakukan monev PIS_PK min setahun sekali, punya SK PIS-PK, Analisis Data dan Roadmap", "nilai_10" => "Melakukan monev PIS_PK min setahun sekali, punya SK PIS-PK Analisis Data dan Roadmap dan melakukan Verifikasi", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            
            ["indikator" => "Manajemen Program", "sub_indikator" => "Program Jejaring", "jenis_variabel" => "Pembinaan Jejaring", "nilai_0" => "tidak ada data dukung", "nilai_4" => "ada program kerja dan kegiatan tapi data dukung belum lengkap", "nilai_7" => "ada program kerja, kegiatan dan dokumentasi tapi data dukung belum lengkap", "nilai_10" => "ada program kerja, kegiatan dan dokumentasi serta data dukung lengkap, dilakukan pembinaan jejaring minimal 1 kali/tahun", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],

            
            
            ["indikator" => "Manajemen Mutu", "sub_indikator" => "Manajemen Mutu", "jenis_variabel" => "Kalibrasi alat kesehatan (Rujukan)", "nilai_0" => "Tidak melakukan kalibrasi", "nilai_4" => "Melakukan 25% dari rencana", "nilai_7" => "Melakukan 75% dari rencana", "nilai_10" => "Melakukan 100 % dari rencana", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Mutu", "sub_indikator" => "Manajemen Mutu", "jenis_variabel" => "Audit Intenal", "nilai_0" => "Tidak melakukan audit internal", "nilai_4" => "Melakukan audit internal min 4 kali/tahun", "nilai_7" => "Melakukan audit internal min 8 kali/tahun", "nilai_10" => "Melakukan audit internal min 12 kali/tahun", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Mutu", "sub_indikator" => "Manajemen Mutu", "jenis_variabel" => "Survei Pelanggan", "nilai_0" => "Tidak melakukan survey pelanggan", "nilai_4" => "Melakukan surcey pelanggan terhadap < 80 pelanggan per tahun", "nilai_7" => "Melakukan survey pelanggan terhadap 80-119 pelanggan per tahun", "nilai_10" => "Melakukan survey pelanggan terhadap 120 pelanggan per tahun", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Mutu", "sub_indikator" => "Manajemen Mutu", "jenis_variabel" => "Rapat tinjauan manajemen", "nilai_0" => "Tidak melakukan rapat tinjauan manajemen", "nilai_4" => "Melakukan rapat tinjauan manajemen minimal 1 kali per tahun", "nilai_7" => "-", "nilai_10" => "Melakukan rapat tinjauan manajemen minimal 2 kali per tahun", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Manajemen Mutu", "sub_indikator" => "Manajemen Mutu", "jenis_variabel" => "Indikator Nasional Mutu (INM) Puskesmas", "nilai_0" => "tidak mengisi aplikasi INM", "nilai_4" => "mengisi dengan hasil rata-rata INM <50%", "nilai_7" => "mengisi dengan hasil rata-rata INM 50% s.d 80%", "nilai_10" => "mengisi dengan hasil rata-rata INM >80%", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],

            
            
            ["indikator" => "Mutu Pelayanan", "sub_indikator" => "Mutu Pelayanan KIA", "jenis_variabel" => "Prosentase tahap proses  pemenuhan Alat Pantau Kinerja Klinis", "nilai_0" => "0-25 %", "nilai_4" => "25-50%", "nilai_7" => "51-75%", "nilai_10" => "76-100%", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            
            ["indikator" => "Mutu Pelayanan", "sub_indikator" => "Mutu Pelayanan Gizi", "jenis_variabel" => "Kepatuhan terhadap SOP gizi buruk", "nilai_0" => "tidak ada", "nilai_4" => "ada 10 daftar tilik", "nilai_7" => "ada 17 daftar tilik", "nilai_10" => "ada 22 daftar tilik", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Mutu Pelayanan", "sub_indikator" => "Mutu Pelayanan Gizi", "jenis_variabel" => "Kepatuhan terhadap SOP promosi ASI Eksklusif", "nilai_0" => "tidak ada", "nilai_4" => "ada 9 daftar tilik", "nilai_7" => "ada 14 daftar tilik", "nilai_10" => "ada 18 daftar tilik", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],

            
            
            ["indikator" => "Inovasi Puskesmas", "sub_indikator" => "Inovasi", "jenis_variabel" => "Inovasi yang dilakukan Puskesmas (Minimal 1 Inovasi yang dinilai)", "nilai_0" => "tidak ada", "nilai_4" => "a. ada inovasi dan sudah berjalan minimal satu tahun", "nilai_7" => "a. ada inovasi dan sudah berjalan minimal satu tahun", "nilai_10" => "a. ada inovasi dan sudah berjalan minimal satu tahun", "nilai_hasil" => "10", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Inovasi Puskesmas", "sub_indikator" => "Inovasi", "jenis_variabel" => "Inovasi yang dilakukan Puskesmas (Minimal 1 Inovasi yang dinilai)", "nilai_0" => "tidak ada", "nilai_4" => "b. ada analisis masalah/ dasar dalam menentukan inovasi dan tertuang dalam RUK", "nilai_7" => "b. ada analisis masalah/ dasar dalam menentukan inovasi dan tertuang dalam RUK", "nilai_10" => "b. ada analisis masalah/ dasar dalam menentukan inovasi dan tertuang dalam RUK", "nilai_hasil" => "0", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Inovasi Puskesmas", "sub_indikator" => "Inovasi", "jenis_variabel" => "Inovasi yang dilakukan Puskesmas (Minimal 1 Inovasi yang dinilai)", "nilai_0" => "tidak ada", "nilai_4" => "c. ada Proporsal dan Paparan Inovasi", "nilai_7" => "c. adanya sistem monitoring dan evaluasi terkait inovasi", "nilai_10" => "c. adanya sistem monitoring dan evaluasi terkait inovasi", "nilai_hasil" => "0", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Inovasi Puskesmas", "sub_indikator" => "Inovasi", "jenis_variabel" => "Inovasi yang dilakukan Puskesmas (Minimal 1 Inovasi yang dinilai)", "nilai_0" => "tidak ada", "nilai_4" => "-", "nilai_7" => "d. ada Proporsal, Paparan Dan Video Inovasi", "nilai_10" => "d. ada kajian untuk menentukan rencana inovasi tahun berikutnya", "nilai_hasil" => "0", "akun_puskesmas" => "Srondol"],
            ["indikator" => "Inovasi Puskesmas", "sub_indikator" => "Inovasi", "jenis_variabel" => "Inovasi yang dilakukan Puskesmas (Minimal 1 Inovasi yang dinilai)", "nilai_0" => "tidak ada", "nilai_4" => "-", "nilai_7" => "-", "nilai_10" => "e. ada Proporsal, Paparan, Video Dan Data Dukung 7 aspek inovasi", "nilai_hasil" => "4", "akun_puskesmas" => "Srondol"]
        
            




            // ["indikator" => "", "sub_indikator" => "", "jenis_variabel" => "", "nilai_0" => "", "nilai_4" => "", "nilai_7" => "", "nilai_10" => "", "nilai_hasil" => "", "akun_puskesmas" => "Srondol"],
          
        ];
        
        
        
        DB::table('tbl_manajemens')->insert($data);
    }
}
